### ISSUE TITLE
Passwords shouldn't be in source code

### ISSUE THREAD

**Issue by nigelhorne** [Monter/spamcop.pl#1]
I found your code because WWW::Mechanize::SpamCop has stopped working since SpamCop moved to https.

Thank you for the code which seems to work seemlessly.

One observation:

Please don't put passwords in source code that is likely to be publicly readable.  Usernames and passwords should be read from a configuration file and that configuration file is then made mode 0600.  I can send you a patch if you want.

**Comment by Monter** [comment]
The script was assumed to be the easiest as possible. If the separation of code and the login data does not require additional Perl modules or a large modification is eager to hear your suggestions for improvements.
