### ISSUE TITLE
Quiet mode?

### ISSUE THREAD

**Issue by nigelhorne** [Monter/spamcop.pl#2]
Is there a quiet mode for running in cron?  I don't want to get e-mails telling me:

:: No report(s) found. Exit.

**Comment by Monter** [comment]
My script does not have a quiet mode. You can set MAILTO="" variable at the start of your crontab file. This will also disable email alert.

**Comment by Monter** [comment]
UPDATE: Try new v.3.3 version, which includes a semi-quiet mode.
